### PR TITLE
Fix for 2.5.2

### PR DESCRIPTION
**Pull request by Morbilio**
Hooks for certain states were removed. Found decent approximation

### CODE REVIEW

**Comment by SC-RRL** [comment]
Is there any chance you can fix ReadAssistant as well? It has the similar problem of missing `HomeSystem.instance` .

**Comment by qysnn** [comment]
Is there any chance you can fix ReadAssistant as well? It has the similar problem of missing `HomeSystem.instance` .

**Comment by Morbilio** [comment]
> Thank you for your work! Is there any chance you can fix ReadAssistant as well? It has the similar problem of missing `HomeSystem.instance` .

Checked in a fix for that as well

**Comment by BeyondW** [comment]
One question, I cannot find dll updates anywhere. Since the version is updated, where can you get the latest dll to read the code change and accommodate it?

**Comment by Morbilio** [comment]
I use UMM modified to not delete the decrypted assembly. Attached is the latest
[Assembly-CSharp.zip](https://github.com/phorcys/Taiwu_mods/files/3564123/Assembly-CSharp.zip)

**Comment by ciwei100000** [comment]
Hi Morbilio! Thank you so much for your contribution. I was one of maintainers for CharacterFloat.cs. I added some new function and opened a pull request #210 . But the pull hasn't been merged. To keep version consistency, would you mind if I merge your fix for CharacterFloat.cs to the pull request #210?

**Pull request merged**
